data=read.table("C:/Users/Shrabanti/Desktop/data.txt",sep=';')
sub_metering1=data[,7]
sub_metering2=data[,8]
sub_metering3=data[,9]
x=data[,2]
plot(x,sub_metering1,col="black",type="l")
points(x,sub_metering2,col="red",type="l")
points(x,sub_metering3,col="blue",type="l")
dev.copy(png,'C:/Users/Shrabanti/Desktop/Plot3.png',width=480,height=480)
dev.off()
